Permutation


Permutation: Rearrangement of elements in a sequence.

Code Explanation: The code randomly shuffles indices of a DataFrame's rows and selects values from an array based on random indices.

Real-Life Usage: Used for randomizing data in machine learning, creating permutations in cryptography, and conducting randomized experiments in statistics.

In simpler terms, the code first mixes up the order of rows in a table-like structure and then randomly grabs items from a box of numbers

In [1]:
#Import Libraries
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
#Create a DataFrame
dframe = DataFrame(np.arange(16).reshape(4,4))

In [3]:
#Generate a Random Permutation
blender = np.random.permutation(4)
blender

array([1, 2, 0, 3])

In [4]:
#Display DataFrame
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
#Reorder DataFrame Rows
dframe.take(blender)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

In [9]:
#Create an Array (Box)
box = np.array([1,2,3])

In [7]:
#Generate Random Integers (Shaker)
shaker = np.random.randint(0,len(box),size=10)
shaker

array([1, 0, 2, 2, 2, 0, 1, 1, 2, 1])

In [8]:
#Select Values from Box
hand_grabs = box.take(shaker)
hand_grabs

array([2, 1, 3, 3, 3, 1, 2, 2, 3, 2])